= UML

Mit Hilfe von UML können Klassendiagramm der Domain Klassen Dargestellt werden

== Beispiel einer UML Klasse

[plantuml]
----
include::UML/SimpleClassExample.puml[]
----

In diesem Diagramm sieht man eine Klasse mit einer Variable foo vom Datentypen String, einer Variable bar vom Datentypen bar und eine Methode baz() die einen boolean zurück gibt.

== Beziehungen zwischen Klassen


[plantuml]
----
include::UML/RelationshipExample.puml[]
----

Die Beziehungen in diesem Diagramm können in drei Arten unterteilt werden:

=== Extension

Eine Extension relationship gibt an, dass eine Klasse von einer anderen erbt. In diesem Beispiel erbt Class1 von Class2 und erhält damit alle Attribute von Class2.

=== Aggregation

Eine Aggregation relationship gibt an, dass ein Child *alleine* ohne seinen Parent existieren kann. In diesem Fall kann Class4 auch ohne Class3 existieren, das heißt, dass wenn ein Objekt von Class4 gelöscht wird, das Objekt von Class3 weiter existieren. In dem Diagramm ist dann noch zusätzlich angegeben, dass Class3 mehrere Instanzen von Class4, aber Class4 nur eine Instanz von Class3 haben kann.

=== Composition

Eine Composition relationship gibt an, dass ein Child *nicht alleine* ohne seinen Parent existieren kann. In diesem Fall kann Class6 nicht ohne Class5 existieren, das heißt, dass wenn ein Objekt von Class5 gelöscht wird auch automatisch die mit ihm assoziierten Objekten von Class6 gelöscht werden. In dem Diagramm ist dann noch zusätzlich angegeben, dass Class5 mehrere Instanzen von Class6, aber Class6 nur eine Instanz von Class5 haben kann.
