# Presentation

Der Presentation-Layer ist für die Rest-Request der Backend-Applikation verantwortlich.

Rest-Request:


|===
|Request |Usage

|GET
|Gibt JSON-Objects zurück

|POST
|Nimmt JSON-OBjects auf, wird hauptsächlich für erstellen von Daten verwendet


|PUT
|Datensatz updaten

|Patch
|teilweise updaten eines Datensatzes

|DELETE
|Datensatz löschen
|===

Für die folgenden Erklärungen wird folgendes Entity verwendet:

[source,Java]
----
@Table(name="user-table")
@Entity
public class User extends AbstractPersistable<Long>
{
private String name;
private Integer age;
private String email;
private LocalDate birthDate;
private Boolean active;
}
----

## REST Controller in Spring Boot

Um Routes für unsere Backend-Applikation zu erstellen, bietet Spring Boot unterschiedliche Annotations für die Rest-Requests an


|===
|Annotation |Request

|@GetMapping
|GET

|@PutMapping
|Put

|@PostMapping
|POST

|@PatchMapping
|PATCH

|@DeleteMapping
|DELETE
|===

Für die folgenden Beispiele erstellen wir eine RestController-Class:

[source,Java]
----
@RestController
@RequestMapping("/api/user")
public class UserRestController {

    private final UserService userService;

}
----

Die Annotation `@RestController` definiert, dass UserRestController eine RestController-Class ist und `@RequestMapping` definiert die Route für den RestController

### GET-Controller

Die folgende Methode ist eine Simple-Get-Methode, welche alle User, die in der Datenbank sind als ein JSON-List zurück gibt.

[source,Java]
----
    @GetMapping("")
    public HttpEntity<List<UserDto>> getAllUser()){
        List<UserDto> userList = userService.getAllUser();
        return (userList.isEmpty())
                ? ResponseEntity.noContent().build()
                : ResponseEntity.ok(userList);
    }
----

Ebenso ist es möglich über den RestController einen Datensatz zu bekommen. Dies kann man verwirklich in dem man die Annotation `@PathVariable` verwendet

[source,Java]
----
    @GetMapping("{id}")
    public HttpEntity<UserDto> getUserbyId(@PathVariable Long id)){
       UserDTO user = userService.getUserbyId(id);
        return (user.isEmpty())
                ? ResponseEntity.noContent().build()
                : ResponseEntity.ok(user);
    }
----

Durch ``@RequestParam`` können wir unsere GET-Methode verschärfern.
Die folgende Methode hat den RequestParam includeResults, welches einen defaultValue no hat. Wenn value von includeResults yes ist, wiedergibt die Methode mehr infos über den User.
[source,Java]
----
@GetMapping("/user/")
    public HttpEntity<List<UserDto>> getUserStatistics(@RequestParam(value="includeResults", defaultValue = "no") String includeResults){
        List<UserDto> userStatistics = null;
        if(includeTestResults.equals("yes")){
            userStatistics = userService.getDetailedUserStatistic();
            return (userStatistics.isEmpty())
                    ? ResponseEntity.noContent().build()
                    : ResponseEntity.ok(userStatistics);
        }
        userStatistics = userService.getPersonStatistic();
        return (userStatistics.isEmpty())
                ? ResponseEntity.noContent().build()
                : ResponseEntity.ok(userStatistics);
    }
----

### POST-Controller


[source,Java]
----
    @PostMapping({"/"})
    public HttpEntity<UserDto> createUser(@RequestBody UserMutateCommand userCreateMutateCommand){
        UserDto user = userService.createUser(userCreateMutateCommand);
        return ResponseEntity.ok().body(userDto);
    }
----

### DELETE-Controlller


[source,Java]
----
    @DeleteMapping({"/{id}"})
    public HttpEntity<UserDto> deleteUser(@PathVariable long id){
        userService.deleteUser(id)
        return ResponseEntity.ok().body(userDto);
    }
----


### PUT-Controller



[source,Java]
----
 @PutMapping("/{id}")
    public HttpEntity<UserDto> replaceUser(@Valid @PathVariable Long id,@RequestBody MutateUserCommand mutateUserCommand){
        return ResponseEntity.ok(new UserDto(userService.replaceUser(id,mutateUserCommand)));
    }

----

### PATCH-Controller


[source,Java]
----
 @PatchMapping({"id"})
    public HttpEntity<UserDto> partiallyUpdateBilling(@PathVariable long id, @Valid @RequestBody MutateUserCommand command) {
        return ResponseEntity.ok(new UserDto(userService.partiallyUpadte(id, command));
    }
----


